### ISSUE TITLE
Get Weather

### ISSUE THREAD

**Issue by CjJordan** [melmealey/Packing-list#3]
As a user I want to be able to find weather for any city so that I can build an appropraite packlinglist for the weather

## Acceptance Criteria

- Make a call to the OpenWeather API with the lat and long and get back current temp
- current temp is logged in the console.

**Comment by melmealey** [comment]
How do I console.log the temp?
console.log(data) is what brought this back (see screenshot)

![Image](https://github.com/melmealey/Packing-list/assets/147653410/d4415e73-6ff3-417a-9c0f-87d14ed7a4c3)

**Comment by melmealey** [comment]
#

**Comment by melmealey** [comment]
It is now working. no errors. logging in °F

<img width="561" alt="Screenshot 2024-01-12 at 8 10 28 PM" src="https://github.com/melmealey/Scheduler/assets/147653410/e721a1ea-5829-441c-8d72-407775de842c">
