### ISSUE TITLE
checkboxes UI

### ISSUE THREAD

**Issue by CjJordan** [melmealey/Packing-list#6]
As a user I want to check items in the suggested packinglist to add them to my list

## Acceptance Criteria

- each suggested item has a check box next to it
- there exists an add button below the list

**Comment by TJoyner2** [comment]
first pull with plenty of issues 

![Image](https://github.com/melmealey/Packing-list/assets/150559721/a414c0fa-efbd-4dc8-acbd-313e98dd171f)
